#!/bin/bash
touch 0-positive_or_negative.c
touch 1-last_digit.c
touch 2-print_alphabet.c
touch 3-print_alphabets.c
touch 4-print_alphabt.c
touch 5-print_numbers.c
touch 6-print_numberz.c
touch 7-print_tebahpla.c
touch 8-print_base16.c
touch 9-print_comb.c
chmod au+x *
